from __future__ import annotations

import typing

import numpy
import scipy.sparse

__all__: list[str] = [
    "Filter",
    "FilterEntry",
    "LdltSystem",
    "KKTSystem",
    "Problem",
    "RelaxationMap",
    "SolveResult",
    "Solver",
    "SolverOptions",
    "Workspace",
]


class Problem:
    @typing.overload
    def __init__(
        self,
        cost_hessian: numpy.ndarray,
        cost_gradient: numpy.ndarray,
        cost_const: float,
        J_eq: numpy.ndarray,
        b_eq: numpy.ndarray,
        J_ineq: numpy.ndarray,
        b_ineq: numpy.ndarray,
        L: numpy.ndarray,
        l: numpy.ndarray,
        R: numpy.ndarray,
        r: numpy.ndarray,
    ) -> None: ...

    @typing.overload
    def __init__(
        self,
        cost_hessian: scipy.sparse.csc_matrix,
        cost_gradient: numpy.ndarray,
        cost_const: float,
        J_eq: scipy.sparse.csc_matrix,
        b_eq: numpy.ndarray,
        J_ineq: scipy.sparse.csc_matrix,
        b_ineq: numpy.ndarray,
        L: scipy.sparse.csc_matrix,
        l: numpy.ndarray,
        R: scipy.sparse.csc_matrix,
        r: numpy.ndarray,
    ) -> None: ...

    def obj(self, z: numpy.ndarray) -> float: ...
    def residual_eq(self, z: numpy.ndarray) -> numpy.ndarray: ...
    def residual_ineq(self, z: numpy.ndarray) -> numpy.ndarray: ...
    def residual_comp_L(self, z: numpy.ndarray) -> numpy.ndarray: ...
    def residual_comp_R(self, z: numpy.ndarray) -> numpy.ndarray: ...
    def residual_comp(self, z: numpy.ndarray) -> numpy.ndarray: ...

    @property
    def nz(self) -> int: ...
    @property
    def n_eq(self) -> int: ...
    @property
    def n_ineq(self) -> int: ...
    @property
    def n_comp(self) -> int: ...
    @property
    def cost_hessian(self) -> tuple[int, int, numpy.ndarray, numpy.ndarray, numpy.ndarray]: ...
    @property
    def cost_gradient(self) -> numpy.ndarray: ...
    @property
    def cost_const(self) -> float: ...
    @property
    def J_eq(self) -> tuple[int, int, numpy.ndarray, numpy.ndarray, numpy.ndarray]: ...
    @property
    def b_eq(self) -> numpy.ndarray: ...
    @property
    def J_ineq(self) -> tuple[int, int, numpy.ndarray, numpy.ndarray, numpy.ndarray]: ...
    @property
    def b_ineq(self) -> numpy.ndarray: ...
    @property
    def L(self) -> tuple[int, int, numpy.ndarray, numpy.ndarray, numpy.ndarray]: ...
    @property
    def l(self) -> numpy.ndarray: ...
    @property
    def R(self) -> tuple[int, int, numpy.ndarray, numpy.ndarray, numpy.ndarray]: ...
    @property
    def r(self) -> numpy.ndarray: ...


class SolverOptions:
    convergence_kkt_norm: float
    convergence_eq_violation: float
    convergence_ineq_violation: float
    convergence_comp_violation: float
    outer_step_kkt_norm: float
    penalty_initial: float
    penalty_max: float
    penalty_scaling: float
    relax_initial: float
    relax_min: float
    relax_scaling: float
    use_relax_correction: bool
    max_iters: int
    max_iters_linesearch: int
    gamma_objective: float
    gamma_constraint: float
    ruiz_iters: int
    verbosity: int

    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...


class FilterEntry:
    feas: float
    merit: float

    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, feas: float, merit: float) -> None: ...


class Filter:
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, gamma_objective: float, gamma_constraint: float) -> None: ...

    def clear(self) -> None: ...
    def sufficient_progress(self, candidate: FilterEntry, entry: FilterEntry) -> tuple[bool, bool]: ...
    def sufficient_feas_progress(self, candidate: FilterEntry, entry: FilterEntry) -> bool: ...
    def sufficient_merit_progress(self, candidate: FilterEntry, entry: FilterEntry) -> bool: ...
    def candidate_acceptable(self, candidate: FilterEntry, entry: FilterEntry) -> bool: ...
    def candidate_dominated(self, candidate: FilterEntry, entry: FilterEntry) -> bool: ...
    def acceptable(self, candidate: FilterEntry) -> bool: ...
    def update(self, new_entry: FilterEntry) -> None: ...

    @property
    def num_entries(self) -> int: ...
    @property
    def entries(self) -> numpy.ndarray: ...


class RelaxationMap:
    def b(self, x: numpy.ndarray, kappa: float) -> numpy.ndarray: ...
    def b_prime(self, x: numpy.ndarray, kappa: float) -> numpy.ndarray: ...
    def b_double_prime(self, x: numpy.ndarray, kappa: float) -> numpy.ndarray: ...
    def d_b_d_kappa(self, x: numpy.ndarray, kappa: float) -> numpy.ndarray: ...
    def d_b_prime_d_kappa(self, x: numpy.ndarray, kappa: float) -> numpy.ndarray: ...
    def d_b_double_prime_d_kappa(self, x: numpy.ndarray, kappa: float) -> numpy.ndarray: ...


class Workspace:
    @property
    def solution(self) -> numpy.ndarray: ...
    @property
    def z(self) -> numpy.ndarray: ...
    @property
    def s_ineq(self) -> numpy.ndarray: ...
    @property
    def s_comp(self) -> numpy.ndarray: ...
    @property
    def m_eq(self) -> numpy.ndarray: ...
    @property
    def m_ineq(self) -> numpy.ndarray: ...
    @property
    def m_comp_L(self) -> numpy.ndarray: ...
    @property
    def m_comp_R(self) -> numpy.ndarray: ...
    @property
    def m_eq_est(self) -> numpy.ndarray: ...
    @property
    def m_ineq_est(self) -> numpy.ndarray: ...
    @property
    def m_comp_L_est(self) -> numpy.ndarray: ...
    @property
    def m_comp_R_est(self) -> numpy.ndarray: ...
    @property
    def residual_eq(self) -> numpy.ndarray: ...
    @property
    def residual_ineq(self) -> numpy.ndarray: ...
    @property
    def residual_comp_L(self) -> numpy.ndarray: ...
    @property
    def residual_comp_R(self) -> numpy.ndarray: ...
    @property
    def relax_param(self) -> float: ...
    @property
    def penalty_param(self) -> float: ...
    @property
    def newton_step_size(self) -> float: ...
    @property
    def newton_step(self) -> numpy.ndarray: ...
    @property
    def relax_correction_step(self) -> numpy.ndarray: ...


class LdltSystem:
    def __init__(self, n: int) -> None: ...
    def factorize(self) -> bool: ...
    def check_inertia(self, n_pos: int, n_neg: int, atol: float = 1e-10) -> bool: ...
    def solve(self, rhs: numpy.ndarray) -> numpy.ndarray: ...
    def problem_to_internal(self, x_problem: numpy.ndarray) -> numpy.ndarray: ...
    def internal_to_problem(self, x_internal: numpy.ndarray) -> numpy.ndarray: ...

    @property
    def built(self) -> bool: ...
    @property
    def matrix(self) -> tuple[int, int, numpy.ndarray, numpy.ndarray, numpy.ndarray]: ...
    @property
    def perm(self) -> numpy.ndarray: ...
    @property
    def iperm(self) -> numpy.ndarray: ...
    @property
    def scaling(self) -> numpy.ndarray: ...


class KKTSystem:
    def ruiz_equilibration(self, niter: int) -> numpy.ndarray: ...
    def update_residual(self) -> None: ...
    def update_kkt_system(self) -> None: ...
    def update_primal_regularizer(self, regularizer: float) -> None: ...
    def update_residual_relax_grad(self) -> None: ...
    def numerical_factorization(self) -> bool: ...
    def check_inertia(self) -> bool: ...
    def compute_step(self, rhs: numpy.ndarray) -> numpy.ndarray: ...

    @property
    def n_primals(self) -> int: ...
    @property
    def n_duals(self) -> int: ...
    @property
    def n_vars(self) -> int: ...
    @property
    def primal_regularizer(self) -> float: ...
    @property
    def residual(self) -> numpy.ndarray: ...
    @property
    def grad_residual_relax_param(self) -> numpy.ndarray: ...
    @property
    def ldlt(self) -> LdltSystem: ...
    @property
    def matrix(self) -> tuple[int, int, numpy.ndarray, numpy.ndarray, numpy.ndarray]: ...
    @property
    def perm(self) -> numpy.ndarray: ...
    @property
    def iperm(self) -> numpy.ndarray: ...
    @property
    def scaling(self) -> numpy.ndarray: ...


class SolveResult:
    converged: bool
    iters: int
    iters_outer: int
    iters_inner: int
    factorizations: int
    factorizations_ldlt: int
    factorizations_inertia: int
    factorizations_linesearch: int
    setup_time_s: float
    solve_time_s: float

    def __repr__(self) -> str: ...

    @property
    def z(self) -> numpy.ndarray: ...
    @property
    def s_ineq(self) -> numpy.ndarray: ...
    @property
    def s_comp(self) -> numpy.ndarray: ...
    @property
    def m_eq(self) -> numpy.ndarray: ...
    @property
    def m_ineq(self) -> numpy.ndarray: ...
    @property
    def m_comp_L(self) -> numpy.ndarray: ...
    @property
    def m_comp_R(self) -> numpy.ndarray: ...
    @property
    def m_comp(self) -> numpy.ndarray: ...


class Solver:
    def __init__(self) -> None: ...
    def set_problem(self, problem: Problem, options: SolverOptions) -> None: ...
    def solve(self) -> SolveResult: ...
    def convergence(self) -> bool: ...
    def get_problem(self) -> Problem: ...
    def get_workspace(self) -> Workspace: ...
    def get_filter(self) -> Filter: ...
    def get_kkt_system(self) -> KKTSystem: ...
    def get_relaxation_map(self) -> RelaxationMap: ...
    def update_relaxed_slack_values(self) -> None: ...
    def update_primal_residuals(self) -> None: ...
    def apply_newton_step(self, step_size: float) -> None: ...
    def filter_linesearch(self) -> bool: ...
    def entry_from_solution(self) -> tuple[float, float]: ...
    def get_options(self) -> SolverOptions: ...

    @property
    def n_primals(self) -> int: ...
    @property
    def n_duals(self) -> int: ...
    @property
    def n_vars(self) -> int: ...
    @property
    def options(self) -> SolverOptions: ...
