"""
Marble compiled core: constrained optimization solver with complementarity constraints
"""
from __future__ import annotations
import numpy
import numpy.typing
import scipy.sparse
import typing
__all__: list[str] = ['Filter', 'FilterEntry', 'Problem', 'RetractionType', 'SolveResult', 'Solver', 'SolverOptions', 'Workspace']
class Filter:
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, gamma_objective: typing.SupportsFloat | typing.SupportsIndex, gamma_constraint: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def acceptable(self, candidate: FilterEntry) -> bool:
        ...
    def candidate_acceptable(self, candidate: FilterEntry, entry: FilterEntry) -> bool:
        ...
    def candidate_dominated(self, candidate: FilterEntry, entry: FilterEntry) -> bool:
        ...
    def clear(self) -> None:
        ...
    def sufficient_progress(self, candidate: FilterEntry, entry: FilterEntry) -> tuple[bool, bool]:
        ...
    def update(self, new_entry: FilterEntry) -> None:
        ...
    @property
    def entries(self) -> list[tuple[float, float]]:
        ...
    @property
    def size(self) -> int:
        ...
class FilterEntry:
    def __init__(self) -> None:
        ...
    def __repr__(self) -> str:
        ...
    @property
    def feas(self) -> float:
        ...
    @feas.setter
    def feas(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def merit(self) -> float:
        ...
    @merit.setter
    def merit(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
class Problem:
    @typing.overload
    def __init__(self, cost_hessian: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"], cost_gradient: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"], cost_const: typing.SupportsFloat | typing.SupportsIndex, J_eq: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"], c_eq: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"], J_ineq: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"], c_ineq: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"], L: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"], l: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"], R: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"], r: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> None:
        ...
    @typing.overload
    def __init__(self, cost_hessian: scipy.sparse.csc_matrix, cost_gradient: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"], cost_const: typing.SupportsFloat | typing.SupportsIndex, J_eq: scipy.sparse.csc_matrix, c_eq: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"], J_ineq: scipy.sparse.csc_matrix, c_ineq: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"], L: scipy.sparse.csc_matrix, l: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"], R: scipy.sparse.csc_matrix, r: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> None:
        ...
    def obj(self, z: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> float:
        ...
    def residual_comp(self, z: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    def residual_eq(self, z: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    def residual_ineq(self, z: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @property
    def J_eq(self) -> tuple[int, int, typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, 1]"], typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, 1]"], typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]]:
        ...
    @property
    def J_ineq(self) -> tuple[int, int, typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, 1]"], typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, 1]"], typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]]:
        ...
    @property
    def L_comp(self) -> tuple[int, int, typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, 1]"], typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, 1]"], typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]]:
        ...
    @property
    def R_comp(self) -> tuple[int, int, typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, 1]"], typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, 1]"], typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]]:
        ...
    @property
    def c_eq(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @property
    def c_ineq(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @property
    def cost_const(self) -> float:
        ...
    @property
    def cost_gradient(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @property
    def cost_hessian(self) -> tuple[int, int, typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, 1]"], typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, 1]"], typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]]:
        ...
    @property
    def l_comp(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @property
    def n_comp(self) -> int:
        ...
    @property
    def n_eq(self) -> int:
        ...
    @property
    def n_ineq(self) -> int:
        ...
    @property
    def nz(self) -> int:
        ...
    @property
    def r_comp(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
class RetractionType:
    """
    Members:
    
      Softplus : p(s) = 0.5 * (s + sqrt(s^2 + 4*kappa))
    
      Exp : p(s) = sqrt(kappa) * exp(s)
    
      ScaledExp : p(s) = sqrt(kappa) * exp(s / sqrt(kappa))
    """
    Exp: typing.ClassVar[RetractionType]  # value = <RetractionType.Exp: 1>
    ScaledExp: typing.ClassVar[RetractionType]  # value = <RetractionType.ScaledExp: 2>
    Softplus: typing.ClassVar[RetractionType]  # value = <RetractionType.Softplus: 0>
    __members__: typing.ClassVar[dict[str, RetractionType]]  # value = {'Softplus': <RetractionType.Softplus: 0>, 'Exp': <RetractionType.Exp: 1>, 'ScaledExp': <RetractionType.ScaledExp: 2>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class SolveResult:
    def __repr__(self) -> str:
        ...
    @property
    def converged(self) -> bool:
        ...
    @property
    def factorizations(self) -> int:
        ...
    @property
    def iterations(self) -> int:
        ...
    @property
    def iterations_inner(self) -> int:
        ...
    @property
    def iterations_outer(self) -> int:
        ...
    @property
    def m_comp_L(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @property
    def m_comp_R(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @property
    def m_eq(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @property
    def m_ineq(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @property
    def s_comp(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @property
    def s_ineq(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @property
    def setup_time_s(self) -> float:
        ...
    @property
    def solve_time_s(self) -> float:
        ...
    @property
    def z(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
class Solver:
    def __init__(self) -> None:
        ...
    def analytical_factorization(self) -> bool:
        ...
    def backsolve(self, b: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    def check_inertia(self) -> bool:
        ...
    def compute_amd_ordering(self) -> None:
        ...
    def convergence(self) -> bool:
        ...
    def entry_from_solution(self, relax_param: typing.SupportsFloat | typing.SupportsIndex, penalty_param: typing.SupportsFloat | typing.SupportsIndex) -> tuple[float, float]:
        ...
    def filter_linesearch(self, relax_param: typing.SupportsFloat | typing.SupportsIndex, penalty_param: typing.SupportsFloat | typing.SupportsIndex, max_iters: typing.SupportsInt | typing.SupportsIndex) -> bool:
        ...
    def get_filter(self) -> Filter:
        ...
    def get_options(self) -> SolverOptions:
        ...
    def get_problem(self) -> Problem:
        ...
    def get_workspace(self) -> Workspace:
        ...
    def initialize_kkt_sparsity(self) -> None:
        ...
    def numerical_factorization(self) -> bool:
        ...
    def retract(self, s: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"], relax_param: typing.SupportsFloat | typing.SupportsIndex) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    def retract_deriv(self, s: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"], relax_param: typing.SupportsFloat | typing.SupportsIndex) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    def retract_second_deriv(self, s: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"], relax_param: typing.SupportsFloat | typing.SupportsIndex) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    def ruiz_equilibration(self, niter: typing.SupportsInt | typing.SupportsIndex) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    def set_problem(self, problem: Problem, options: SolverOptions) -> None:
        ...
    def solve(self) -> SolveResult:
        ...
    def update_KKT_comp(self, s_comp: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"], m_comp_L: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"], m_comp_R: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"], relax_param: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def update_KKT_ineq(self, s_ineq: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"], relax_param: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def update_KKT_penalty(self, penalty_param: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def update_KKT_primal_regularizer(self, reg: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def update_KKT_residual(self, relax_param: typing.SupportsFloat | typing.SupportsIndex, penalty_param: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def update_KKT_system(self, relax_param: typing.SupportsFloat | typing.SupportsIndex, penalty_param: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def update_residuals(self) -> None:
        ...
    @property
    def m_comp_L_inds(self) -> typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, 1]"]:
        ...
    @property
    def m_comp_R_inds(self) -> typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, 1]"]:
        ...
    @property
    def m_eq_inds(self) -> typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, 1]"]:
        ...
    @property
    def m_ineq_inds(self) -> typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, 1]"]:
        ...
    @property
    def n_duals(self) -> int:
        ...
    @property
    def n_primals(self) -> int:
        ...
    @property
    def n_vars(self) -> int:
        ...
    @property
    def s_comp_inds(self) -> typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, 1]"]:
        ...
    @property
    def s_comp_m_comp_L_inds(self) -> typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, 1]"]:
        ...
    @property
    def s_comp_m_comp_R_inds(self) -> typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, 1]"]:
        ...
    @property
    def s_comp_s_comp_inds(self) -> typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, 1]"]:
        ...
    @property
    def s_ineq_inds(self) -> typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, 1]"]:
        ...
    @property
    def s_ineq_m_ineq_inds(self) -> typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, 1]"]:
        ...
    @property
    def s_ineq_s_ineq_inds(self) -> typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, 1]"]:
        ...
    @property
    def z_inds(self) -> typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, 1]"]:
        ...
    @property
    def z_z_inds(self) -> typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, 1]"]:
        ...
class SolverOptions:
    clamp_hessian: bool
    comp_init_random: bool
    inertia_warmstart: bool
    retraction_type: RetractionType
    def __init__(self) -> None:
        ...
    def __repr__(self) -> str:
        ...
    @property
    def comp_init_seed(self) -> int:
        ...
    @comp_init_seed.setter
    def comp_init_seed(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def convergence_comp_violation(self) -> float:
        ...
    @convergence_comp_violation.setter
    def convergence_comp_violation(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def convergence_eq_violation(self) -> float:
        ...
    @convergence_eq_violation.setter
    def convergence_eq_violation(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def convergence_ineq_violation(self) -> float:
        ...
    @convergence_ineq_violation.setter
    def convergence_ineq_violation(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def convergence_kkt_norm(self) -> float:
        ...
    @convergence_kkt_norm.setter
    def convergence_kkt_norm(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def gamma_constraint(self) -> float:
        ...
    @gamma_constraint.setter
    def gamma_constraint(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def gamma_objective(self) -> float:
        ...
    @gamma_objective.setter
    def gamma_objective(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def max_iters(self) -> int:
        ...
    @max_iters.setter
    def max_iters(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def max_iters_linesearch(self) -> int:
        ...
    @max_iters_linesearch.setter
    def max_iters_linesearch(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def outer_step_kkt_norm(self) -> float:
        ...
    @outer_step_kkt_norm.setter
    def outer_step_kkt_norm(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def penalty_initial(self) -> float:
        ...
    @penalty_initial.setter
    def penalty_initial(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def penalty_max(self) -> float:
        ...
    @penalty_max.setter
    def penalty_max(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def penalty_scaling(self) -> float:
        ...
    @penalty_scaling.setter
    def penalty_scaling(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def relaxation_initial(self) -> float:
        ...
    @relaxation_initial.setter
    def relaxation_initial(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def relaxation_min(self) -> float:
        ...
    @relaxation_min.setter
    def relaxation_min(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def relaxation_scaling(self) -> float:
        ...
    @relaxation_scaling.setter
    def relaxation_scaling(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def ruiz_iterations(self) -> int:
        ...
    @ruiz_iterations.setter
    def ruiz_iterations(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def verbosity(self) -> int:
        ...
    @verbosity.setter
    def verbosity(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class Workspace:
    @property
    def D(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @property
    def amd_iperm_vec(self) -> typing.Annotated[numpy.typing.NDArray[numpy.int64], "[m, 1]"]:
        ...
    @property
    def amd_perm_vec(self) -> typing.Annotated[numpy.typing.NDArray[numpy.int64], "[m, 1]"]:
        ...
    @property
    def kkt_residual(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @property
    def kkt_system(self) -> tuple[int, int, typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, 1]"], typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, 1]"], typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]]:
        ...
    @property
    def m_comp_L(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @property
    def m_comp_L_est(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @property
    def m_comp_R(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @property
    def m_comp_R_est(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @property
    def m_eq(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @property
    def m_eq_est(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @property
    def m_ineq(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @property
    def m_ineq_est(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @property
    def newton_step(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @property
    def penalty_param(self) -> float:
        ...
    @property
    def relax_param(self) -> float:
        ...
    @property
    def residual_comp_L(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @property
    def residual_comp_R(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @property
    def residual_eq(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @property
    def residual_ineq(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @property
    def s_comp(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @property
    def s_ineq(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @property
    def scaling(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @property
    def solution(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @property
    def z(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
