"""
Marble: constrained optimization solver with complementarity constraints
"""
from __future__ import annotations
import numpy
import scipy.sparse
import typing
__all__: list[str] = ['Filter', 'FilterEntry', 'Problem', 'SolveResult', 'Solver', 'SolverOptions', 'Workspace']
class Filter:
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, gamma_objective: float, gamma_constraint: float) -> None:
        ...
    def acceptable(self, candidate: FilterEntry) -> bool:
        ...
    def candidate_acceptable(self, candidate: FilterEntry, entry: FilterEntry) -> bool:
        ...
    def candidate_dominated(self, candidate: FilterEntry, entry: FilterEntry) -> bool:
        ...
    def clear(self) -> None:
        ...
    def sufficient_progress(self, candidate: FilterEntry, entry: FilterEntry) -> tuple[bool, bool]:
        ...
    def update(self, new_entry: FilterEntry) -> None:
        ...
    @property
    def entries(self) -> list[tuple[float, float]]:
        ...
    @property
    def size(self) -> int:
        ...
class FilterEntry:
    feas: float
    merit: float
    def __init__(self) -> None:
        ...
    def __repr__(self) -> str:
        ...
class Problem:
    @typing.overload
    def __init__(self, cost_hessian: numpy.ndarray, cost_gradient: numpy.ndarray, cost_const: float, J_eq: numpy.ndarray, c_eq: numpy.ndarray, J_ineq: numpy.ndarray, c_ineq: numpy.ndarray, L: numpy.ndarray, l: numpy.ndarray, R: numpy.ndarray, r: numpy.ndarray) -> None:
        ...
    @typing.overload
    def __init__(self, cost_hessian: scipy.sparse.csc_matrix, cost_gradient: numpy.ndarray, cost_const: float, J_eq: scipy.sparse.csc_matrix, c_eq: numpy.ndarray, J_ineq: scipy.sparse.csc_matrix, c_ineq: numpy.ndarray, L: scipy.sparse.csc_matrix, l: numpy.ndarray, R: scipy.sparse.csc_matrix, r: numpy.ndarray) -> None:
        ...
    @property
    def J_comp(self) -> tuple:
        ...
    @property
    def J_eq(self) -> tuple:
        ...
    @property
    def J_ineq(self) -> tuple:
        ...
    @property
    def c_comp(self) -> numpy.ndarray:
        ...
    @property
    def c_eq(self) -> numpy.ndarray:
        ...
    @property
    def c_ineq(self) -> numpy.ndarray:
        ...
    @property
    def cost_const(self) -> float:
        ...
    @property
    def cost_gradient(self) -> numpy.ndarray:
        ...
    @property
    def cost_hessian(self) -> tuple:
        ...
    @property
    def n_comp(self) -> int:
        ...
    @property
    def n_eq(self) -> int:
        ...
    @property
    def n_ineq(self) -> int:
        ...
    @property
    def nz(self) -> int:
        ...
class SolveResult:
    def __repr__(self) -> str:
        ...
    @property
    def converged(self) -> bool:
        ...
    @property
    def factorizations(self) -> int:
        ...
    @property
    def iterations(self) -> int:
        ...
    @property
    def iterations_inner(self) -> int:
        ...
    @property
    def iterations_outer(self) -> int:
        ...
    @property
    def m_comp(self) -> numpy.ndarray:
        ...
    @property
    def m_eq(self) -> numpy.ndarray:
        ...
    @property
    def m_ineq(self) -> numpy.ndarray:
        ...
    @property
    def s_comp(self) -> numpy.ndarray:
        ...
    @property
    def s_ineq(self) -> numpy.ndarray:
        ...
    @property
    def setup_time_s(self) -> float:
        ...
    @property
    def solve_time_s(self) -> float:
        ...
    @property
    def z(self) -> numpy.ndarray:
        ...
class Solver:
    def __init__(self) -> None:
        ...
    def analytical_factorization(self) -> bool:
        ...
    def backsolve(self) -> None:
        ...
    def check_inertia(self) -> bool:
        ...
    def compute_amd_ordering(self) -> None:
        ...
    def convergence(self, options: SolverOptions) -> bool:
        ...
    def entry_from_solution(self, sqrt_relax_param: float, inv_penalty_param: float) -> tuple:
        ...
    def filter_linesearch(self, sqrt_relax_param: float, inv_penalty_param: float, max_iters: int) -> bool:
        ...
    def get_filter(self) -> Filter:
        ...
    def get_problem(self) -> Problem:
        ...
    def get_workspace(self) -> Workspace:
        ...
    def initialize_kkt_sparsity(self) -> None:
        ...
    def numerical_factorization(self) -> bool:
        ...
    def retract(self, s: numpy.ndarray, sqrt_relax_param: float) -> numpy.ndarray:
        ...
    def retract_deriv(self, s: numpy.ndarray, sqrt_relax_param: float) -> numpy.ndarray:
        ...
    def retract_second_deriv(self, s: numpy.ndarray, sqrt_relax_param: float) -> numpy.ndarray:
        ...
    def ruiz_equilibration(self, niter: int) -> numpy.ndarray:
        ...
    @typing.overload
    def set_problem(self, cost_hessian: numpy.ndarray, cost_gradient: numpy.ndarray, cost_const: float, J_eq: numpy.ndarray, c_eq: numpy.ndarray, J_ineq: numpy.ndarray, c_ineq: numpy.ndarray, L: numpy.ndarray, l: numpy.ndarray, R: numpy.ndarray, r: numpy.ndarray, options: SolverOptions) -> None:
        ...
    @typing.overload
    def set_problem(self, cost_hessian: scipy.sparse.csc_matrix, cost_gradient: numpy.ndarray, cost_const: float, J_eq: scipy.sparse.csc_matrix, c_eq: numpy.ndarray, J_ineq: scipy.sparse.csc_matrix, c_ineq: numpy.ndarray, L: scipy.sparse.csc_matrix, l: numpy.ndarray, R: scipy.sparse.csc_matrix, r: numpy.ndarray, options: SolverOptions) -> None:
        ...
    def solve(self) -> SolveResult:
        ...
    def update_KKT_comp(self, s_comp: numpy.ndarray, m_comp: numpy.ndarray, sqrt_relax_param: float) -> None:
        ...
    def update_KKT_ineq(self, s_ineq: numpy.ndarray, sqrt_relax_param: float) -> None:
        ...
    def update_KKT_penalty(self, inv_penalty_param: float) -> None:
        ...
    def update_KKT_primal_regularizer(self, reg: float) -> None:
        ...
    def update_KKT_residual(self, sqrt_relax_param: float, inv_penalty_param: float) -> None:
        ...
    def update_KKT_system(self, sqrt_relax_param: float, inv_penalty_param: float) -> None:
        ...
    @property
    def comp_L_inds(self) -> numpy.ndarray:
        ...
    @property
    def comp_R_inds(self) -> numpy.ndarray:
        ...
    @property
    def m_comp_inds(self) -> numpy.ndarray:
        ...
    @property
    def m_eq_inds(self) -> numpy.ndarray:
        ...
    @property
    def m_ineq_inds(self) -> numpy.ndarray:
        ...
    @property
    def n_duals(self) -> int:
        ...
    @property
    def n_primals(self) -> int:
        ...
    @property
    def n_vars(self) -> int:
        ...
    @property
    def s_comp_inds(self) -> numpy.ndarray:
        ...
    @property
    def s_comp_m_comp_inds(self) -> numpy.ndarray:
        ...
    @property
    def s_comp_s_comp_inds(self) -> numpy.ndarray:
        ...
    @property
    def s_ineq_inds(self) -> numpy.ndarray:
        ...
    @property
    def s_ineq_m_ineq_inds(self) -> numpy.ndarray:
        ...
    @property
    def s_ineq_s_ineq_inds(self) -> numpy.ndarray:
        ...
    @property
    def z_inds(self) -> numpy.ndarray:
        ...
    @property
    def z_z_inds(self) -> numpy.ndarray:
        ...
class SolverOptions:
    convergence_comp_violation: float
    convergence_eq_violation: float
    convergence_ineq_violation: float
    convergence_kkt_norm: float
    debug: bool
    debug_log_every: int
    debug_output_path: str
    gamma_constraint: float
    gamma_objective: float
    max_iters: int
    max_iters_linesearch: int
    outer_step_kkt_norm: float
    output_dir: str
    penalty_initial: float
    penalty_max: float
    penalty_scaling: float
    print_every: int
    relaxation_initial: float
    relaxation_min: float
    relaxation_scaling: float
    ruiz_iterations: int
    verbosity: int
    def __init__(self) -> None:
        ...
    def __repr__(self) -> str:
        ...
class Workspace:
    @property
    def D(self) -> numpy.ndarray:
        ...
    @property
    def amd_iperm_vec(self) -> numpy.ndarray:
        ...
    @property
    def amd_perm_vec(self) -> numpy.ndarray:
        ...
    @property
    def kkt_residual(self) -> numpy.ndarray:
        ...
    @property
    def kkt_system(self) -> tuple:
        ...
    @property
    def m_comp(self) -> numpy.ndarray:
        ...
    @property
    def m_comp_est(self) -> numpy.ndarray:
        ...
    @property
    def m_eq(self) -> numpy.ndarray:
        ...
    @property
    def m_eq_est(self) -> numpy.ndarray:
        ...
    @property
    def m_ineq(self) -> numpy.ndarray:
        ...
    @property
    def m_ineq_est(self) -> numpy.ndarray:
        ...
    @property
    def newton_step(self) -> numpy.ndarray:
        ...
    @property
    def penalty_param(self) -> float:
        ...
    @property
    def relax_param(self) -> float:
        ...
    @property
    def residual_comp(self) -> numpy.ndarray:
        ...
    @property
    def residual_eq(self) -> numpy.ndarray:
        ...
    @property
    def residual_ineq(self) -> numpy.ndarray:
        ...
    @property
    def s_comp(self) -> numpy.ndarray:
        ...
    @property
    def s_ineq(self) -> numpy.ndarray:
        ...
    @property
    def scaling(self) -> numpy.ndarray:
        ...
    @property
    def solution(self) -> numpy.ndarray:
        ...
    @property
    def z(self) -> numpy.ndarray:
        ...
